import type { NextPage } from 'next'
import Head from 'next/head'

import Header from '../src/components/header'

import Login from '../src/components/auth/login'

import Wrapper from '../src/components/wrapper'

const Home: NextPage = () => {
  return (
    <div className='overflow-x-hidden'>
      <Head>
        <title>Вход</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Wrapper>
              <Login/>
      </Wrapper>

    </div>
  )
}

export default Home
