import type { NextPage } from 'next'
import Head from 'next/head'

import Header from '../src/components/header'
import Navbar from '../src/components/navbar'
import Main from '../src/components/main-page/main'

import Wrapper from '../src/components/wrapper'

const Home: NextPage = () => {
  return (
    <div className='overflow-x-hidden'>
      <Head>
        <title>Метафорика 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Navbar islogged={false} />
      <Wrapper >
        <Main />
      </Wrapper>
      
    </div>
  )
}

export default Home
