import type { NextPage } from "next"
import Head from "next/head"

import Header from "../src/components/molecules/header"

import Page_Wrapper from "../src/components/atoms/page_wrapper"

const Projects: NextPage = () => {
  return (
    <>
      <Head>
        <title>leosh1d</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}

export default Projects
