import type { NextPage } from "next"
import Head from "next/head"

import Header from "../src/components/header"

import Register from "../src/components/auth/register"

import Wrapper from "../src/components/wrapper"

const Home: NextPage = () => {
  return (
    <div className="overflow-x-hidden">
      <Head>
        <title>Вход</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Wrapper>
        <Register />
      </Wrapper>
    </div>
  )
}

export default Home
