import type { NextPage } from "next"
import Head from "next/head"

const Skills: NextPage = () => {
  return (
    <>
      <Head>
        <title>leosh1d</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}

export default Skills
